"""
Report generation service
"""

from typing import Dict, Any
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from io import BytesIO
from datetime import datetime

def generate_json_report(query) -> Dict[str, Any]:
    """Generate structured JSON report"""
    return {
        "report_metadata": {
            "query_id": query.id,
            "query_type": query.query_type,
            "query_value": query.query_value,
            "risk_score": query.risk_score,
            "created_at": query.created_at.isoformat() if query.created_at else None,
            "generated_at": datetime.utcnow().isoformat()
        },
        "disclaimer": "This report contains only publicly available information. For educational, investigative, and defensive security purposes only.",
        "results": query.results if query.results else {},
        "source_attribution": "All data points include source attribution. No private or unauthorized data accessed."
    }

def generate_pdf_report(query) -> bytes:
    """Generate PDF report"""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    story = []
    
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor='#00ff00',
        spaceAfter=30,
        alignment=TA_CENTER
    )
    
    # Title
    story.append(Paragraph("OSINT Investigation Report", title_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Disclaimer
    disclaimer_style = ParagraphStyle(
        'Disclaimer',
        parent=styles['Normal'],
        fontSize=10,
        textColor='#ff0000',
        backColor='#ffff00',
        borderPadding=10
    )
    story.append(Paragraph(
        "<b>LEGAL DISCLAIMER:</b> This report contains only publicly available information. "
        "For educational, investigative, and defensive security purposes only. "
        "No private or unauthorized data accessed.",
        disclaimer_style
    ))
    story.append(Spacer(1, 0.3*inch))
    
    # Query Information
    story.append(Paragraph(f"<b>Query Type:</b> {query.query_type}", styles['Normal']))
    story.append(Paragraph(f"<b>Query Value:</b> {query.query_value}", styles['Normal']))
    story.append(Paragraph(f"<b>Risk Score:</b> {query.risk_score}", styles['Normal']))
    story.append(Paragraph(f"<b>Created At:</b> {query.created_at}", styles['Normal']))
    story.append(Spacer(1, 0.2*inch))
    
    # Results
    if query.results:
        story.append(Paragraph("<b>Investigation Results:</b>", styles['Heading2']))
        story.append(Spacer(1, 0.1*inch))
        
        results = query.results
        if isinstance(results, dict):
            if "results" in results:
                for result in results.get("results", []):
                    source = result.get("source", "Unknown")
                    confidence = result.get("confidence", "N/A")
                    story.append(Paragraph(f"<b>Source:</b> {source} (Confidence: {confidence})", styles['Normal']))
                    story.append(Spacer(1, 0.1*inch))
    
    # Footer
    story.append(PageBreak())
    story.append(Paragraph(
        "Report generated by OSINT Tool - Educational Use Only",
        ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, alignment=TA_CENTER)
    ))
    
    doc.build(story)
    buffer.seek(0)
    return buffer.read()

